spring:
  kafka:
    producer:
      bootstrapServers: localhost:9092
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer

    topicName:
      wikimediaRecentChange: "wikimedia-recent-change-topic"
