spring:
  kafka:
    consumer:
      bootstrapServers: localhost:9092
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    topicName:
      wikimediaRecentChange: "wikimedia-recent-change-topic"
