server:
  port: 8082

spring:
  kafka:
    consumer:
      bootstrapServers: localhost:9092
      groupId: ${spring.kafka.groupId.demo}
      autoOffsetReset: earliest
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer

    topicName:
      wikimediaRecentChange: "wikimedia-recent-change-topic"

    groupId:
      demo: "demo-group"

  datasource:
    url: jdbc:postgresql://localhost:5432/wikimedia_db
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddlAuto: create-drop
    showSql: false

    # Performance optimization purposes, makes SQL execute faster
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect

    # This must be set to `true` so `data.sql` can be run
    deferDatasourceInitialization: false

  sql:
    init:
      mode: always
      platform: postgres
