spring:
  kafka:
    consumer:
      bootstrapServers: localhost:9092
      groupId: ${spring.kafka.groupId.demo}
      autoOffsetReset: earliest
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer

    topicName:
      wikimediaRecentChange: "wikimedia-recent-change-topic"

    groupId:
      demo: "demo-group"
